[package]
name = "pp-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pp"
path = "src/main.rs"

[dependencies]
pp-store   = { workspace = true }
pp-events  = { workspace = true }
pp-domain  = { workspace = true, features = ["serde"] }
clap       = { workspace = true }
tokio      = { workspace = true }
async-nats = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
anyhow     = "1"
time       = { workspace = true }
